export default () => {
    return (
        <div>

            <div>globalConfig</div>
            <div>globalConfig</div>
            <div>globalConfig</div>
            <div>globalConfig</div>
            <div>globalConfig</div>
            <div>globalConfig</div>
            <div>globalConfig</div>
            <div>globalConfig</div>
            <div>globalConfig</div>
            <div>globalConfig</div>
            <div>globalConfig</div>
            <div>globalConfig</div>
            <div>globalConfig</div>
            <div>globalConfig</div>
            <div>globalConfig</div>
            <div>globalConfig</div>
            <div>globalConfig</div>
            <div>globalConfig</div>
            <div>globalConfig</div>
            <div>globalConfig</div>
            <div>globalConfig</div>
            <div>globalConfig</div>
            <div>globalConfig</div>
            <div>globalConfig</div>
            <div>globalConfig</div>
            <div>globalConfig</div>
            <div>globalConfig</div>
            <div>globalConfig</div>
            <div>globalConfig</div>
            <div>globalConfig</div>
            <div>globalConfig</div>
            <div>globalConfig</div>
            <div>globalConfig</div>
            <div>globalConfig</div>
            <div>globalConfig</div>
            <div>globalConfig</div>
            <div>globalConfig</div>
            <div>globalConfig</div>
            <div>globalConfig</div>
            <div>globalConfig</div>
            <div>globalConfig</div>
            <div>globalConfig</div>
            <div>globalConfig</div>
            <div>globalConfig</div>
            <div>globalConfig</div>

        </div>
    )
}